" vimrc - vim configuration

set nocompatible

execute pathogen#infect()
execute pathogen#helptags()

if has('autocmd')
  filetype plugin indent on
endif

if has('syntax')
  syntax on
endif

" Default Options
"set nobackup
set noerrorbells
set nojoinspaces
"set noswapfile
set nowrap

" Protect changes between writes. Default values of
" updatecount (200 keystrokes) and updatetime
" (4 seconds) are fine
set swapfile
set directory^=~/.vim/swap//

" protect against crash-during-write
set writebackup
" but do not persist backup after successful write
set nobackup
" use rename-and-write-new method whenever safe
set backupcopy=auto
" patch required to honor double slash at end
if has("patch-8.1.0251")
  " consolidate the writebackups -- not a big
  " deal either way, since they usually get deleted
  set backupdir^=~/.vim/backup//
end

" persist the undo tree for each file
set undofile
set undodir^=~/.vim/undo//

set autowrite
set backspace=indent,eol,start
set hidden
set ignorecase
set laststatus=2
set lazyredraw
set modeline
set number
set ruler
set showmatch
set showmode
set smartcase
set splitright
set switchbuf=usetab
set timeoutlen=2000
set ttimeoutlen=0
set ttyfast

set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc,*/build/,build/**
set wildmenu                                                 " show a navigable menu for tab completion
set wildmode=longest:list

set autoread                                                 " reload files when changed on disk, i.e. via `git checkout`
set directory-=.                                             " don't store swapfiles in the current directory
set encoding=utf-8
set incsearch                                                " search as you type
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,trail:▫

" Feature Options
if has('clipboard')
  set clipboard=unnamed
  if has('unnamedplus')
    set clipboard+=unnamedplus
  endif
endif

if has('diff')
  set diffopt=filler,context:3
endif

if has('extra_search')
  set nohlsearch
endif

if has('folding')
  set foldenable
  set foldlevelstart=20
  "set foldmethod=syntax
endif

if has('mksession')
  set sessionoptions-=buffers
endif

if has('mouse')
  set mouse=a
  if has('mouse_sgr')
    set ttymouse=sgr
  endif

  if exists('$TMUX')  " Support resizing in tmux
    set ttymouse=xterm2
  endif
endif

" if has('syntax')
  " set cursorline
" endif

if has('windows')
  set showtabline=2
  set winminheight=0
endif

" Default Indentation
set autoindent
set shiftround
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=8
set textwidth=72

" Other
" set cursorline
" set cursorcolumn
" Key Mappings

let mapleader = ','
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

nnoremap <leader>] :TagbarToggle<CR>

" noremap <C-J> <PageDown>
" noremap <C-K> <PageUp>

noremap <silent> <Leader>n :set hlsearch!<CR>
noremap <silent> <Leader>p :set paste!<CR>
noremap <silent> <Leader>r :set relativenumber!<CR>
noremap <silent> <Leader>s :set spell!<CR>
noremap <silent> <leader>x :Hexmode <CR>
noremap <silent> <leader>c :ClangFormat <CR>

noremap <silent> [b :bprevious<CR>
noremap <silent> ]b :bnext<CR>

noremap <silent> [t :tabprev<CR>
noremap <silent> ]t :tabnext<CR>

nnoremap <leader><space> :WhitespaceStrip<CR>
nnoremap <leader>g :GitGutterToggle<CR>

" Remote terminals don't cope particularly well with arrow keys in
" insert mode. The key mappings proposed in Solution 15 works around the
" issue without having to modify the 'term' option;
" see: http://vim.wikia.com/wiki/Fix_arrow_keys_that_display_A_B_C_D_on_remote_shell.
inoremap <Esc>oA <Esc>ki
inoremap <Esc>oB <Esc>ji
inoremap <Esc>oC <Esc>li
inoremap <Esc>oD <Esc>hi

map Q <Nop>

" fdoc is yaml
autocmd BufRead,BufNewFile *.fdoc set filetype=yaml
" md is markdown
autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd BufRead,BufNewFile *.md set spell

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

let g:whitespace_strip_enabled = 1

let g:whitespace_ignore_tabs = [
      \ 'git',
      \ 'gitcommit',
      \ 'gitconfig',
      \ 'gitrebase',
      \ 'gitsendemail',
      \ ]

" Fix Cursor in TMUX
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" Color Scheme
colorscheme wtf

set statusline+=%{gutentags#statusline()}

"let g:ycm_global_ycm_extra_conf='~/.vim/.ycm_extra_conf.py'
"let g:loaded_youcompleteme=1

let g:ycm_min_num_of_chars_for_completion = 99
let g:ycm_autoclose_preview_window_after_completion = 1
"let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_confirm_extra_conf = 0
let g:ycm_use_clangd = 0


noremap <leader>jd :YcmCompleter GoTo<CR>

let g:CommandTFileScanner="git"
let g:CommandTMaxFiles=250000
let g:gutentags_enabled=1
let g:gutentags_generate_on_missing=1

let g:clang_format#style_options = {
      \ "BasedOnStyle" : "google",
      \ "ColumnLimit" : 100,
      \ "BinPackArguments" : "false",
      \ "BinPackParameters" : "false",
      \ "AllowShortFunctionsOnASingleLine" : "Inline",
      \ "SortUsingDeclarations" : "true"}

let g:clang_format#detect_style_file = 1
let g:clang_format#enable_fallback_style = 0

autocmd FileType cpp ClangFormatAutoEnable
autocmd FileType c ClangFormatAutoEnable

autocmd FileType python set softtabstop=2

" Splits
" window
nmap <leader>swh :topleft  vnew<CR>
nmap <leader>swl :botright vnew<CR>
nmap <leader>swk :topleft  new<CR>
nmap <leader>swj :botright new<CR>
" buffer
nmap <leader>sh  :leftabove  vnew<CR>
nmap <leader>sl  :rightbelow vnew<CR>
nmap <leader>sk  :leftabove  new<CR>
nmap <leader>sj  :rightbelow new<CR>

" Source local configuration:
"silent! source ~/.vimrc.local
