# zshrc - zsh configuration

bindkey -v
bindkey "^?" backward-delete-char
bindkey "^H" backward-delete-char

limit coredumpsize unlimited

# Disable flow control and freeze terminal settings:
stty -ixon
ttyctl -f

setopt NO_ALWAYS_LAST_PROMPT
setopt NO_AUTO_REMOVE_SLASH
setopt NO_HIST_BEEP
setopt NO_LIST_BEEP
setopt NO_PROMPT_SP

setopt COMPLETE_ALIASES
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt INC_APPEND_HISTORY
setopt MAGIC_EQUAL_SUBST
setopt PUSHD_IGNORE_DUPS
setopt RM_STAR_SILENT

export EDITOR=vim
export PAGER=less

# Rather than clutter zshrc, we source configuration from zshrc.d to
# further customize the shell:
for file in ~/.zshrc.d/*; do
	source $file
done
unset file

# vim: ft=zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# The next line updates PATH for the Google Cloud SDK.
#if [ -f '/Users/bridder/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/bridder/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
#if [ -f '/Users/bridder/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/bridder/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
#export PATH="/Users/bridder/workspace/brew/opt/ruby/bin:$PATH"

export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'


# Created by `pipx` on 2023-10-05 20:46:36
export PATH="$PATH:/Users/ben/.local/bin"

export STM32_PRG_PATH=/Applications/STMicroelectronics/STM32Cube/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOs/bin

export STM32CubeMX_PATH=/Applications/STMicroelectronics/STM32CubeMX.app/Contents/Resources